// Mock data for the marketplace (CodeCanyon-style)

export interface MarketItem {
  id: string;
  slug: string;
  title: string;
  category: string;
  subcategory: string;
  author: string;
  authorAvatar: string;
  price: number;
  rating: number;
  reviews: number;
  sales: number;
  thumbnail: string;
  tags: string[];
  lastUpdate: string;
  created: string;
  version: string;
  description: string;
  status: "live" | "pending" | "rejected" | "draft" | "soft_rejected";
}

const COVERS = [
  "linear-gradient(135deg,#EB0045,#0033A1)",
  "linear-gradient(135deg,#00A7E1,#2ED9C3)",
  "linear-gradient(135deg,#0033A1,#00A7E1)",
  "linear-gradient(135deg,#00205C,#EB0045)",
  "linear-gradient(135deg,#2ED9C3,#0033A1)",
  "linear-gradient(135deg,#EB0045,#00A7E1)",
  "linear-gradient(135deg,#00205C,#2ED9C3)",
  "linear-gradient(135deg,#0033A1,#EB0045)",
];

export function coverFor(id: string) {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  return COVERS[h % COVERS.length];
}

export const ITEMS: MarketItem[] = [
  {
    id: "i1",
    slug: "novapress-saas-wordpress-theme",
    title: "NovaPress — SaaS & Startup WordPress Theme",
    category: "wordpress",
    subcategory: "Business",
    author: "PixelStack",
    authorAvatar: "PS",
    price: 59,
    rating: 4.8,
    reviews: 1240,
    sales: 12450,
    thumbnail: "",
    tags: ["wordpress", "saas", "startup", "elementor"],
    lastUpdate: "2024-12-10",
    created: "2022-04-12",
    version: "4.2.1",
    description: "Modern, fast, fully responsive SaaS theme for WordPress with Elementor builder.",
    status: "live",
  },
  {
    id: "i2",
    slug: "shopfast-react-ecommerce",
    title: "ShopFast — React eCommerce Template",
    category: "html-templates",
    subcategory: "Retail",
    author: "DevOrbit",
    authorAvatar: "DO",
    price: 29,
    rating: 4.7,
    reviews: 845,
    sales: 8230,
    thumbnail: "",
    tags: ["react", "ecommerce", "tailwind", "next.js"],
    lastUpdate: "2024-11-28",
    created: "2023-01-08",
    version: "2.5.0",
    description: "Production-ready React eCommerce template with cart, checkout and admin.",
    status: "live",
  },
  {
    id: "i3",
    slug: "bizpro-admin-dashboard",
    title: "BizPro — Admin Dashboard Kit",
    category: "html-templates",
    subcategory: "Admin",
    author: "ThemeNest",
    authorAvatar: "TN",
    price: 39,
    rating: 4.9,
    reviews: 2104,
    sales: 18920,
    thumbnail: "",
    tags: ["dashboard", "admin", "tailwind", "charts"],
    lastUpdate: "2024-12-01",
    created: "2021-11-22",
    version: "6.1.0",
    description: "60+ pages, dark mode, RTL support, and 12 chart variants included.",
    status: "live",
  },
  {
    id: "i4",
    slug: "laravel-crm-pro",
    title: "Laravel CRM Pro — Customer Management",
    category: "php-scripts",
    subcategory: "CRM",
    author: "CodeMatrix",
    authorAvatar: "CM",
    price: 49,
    rating: 4.6,
    reviews: 432,
    sales: 3210,
    thumbnail: "",
    tags: ["laravel", "crm", "php", "mysql"],
    lastUpdate: "2024-12-05",
    created: "2022-08-19",
    version: "3.0.0",
    description: "Full-featured CRM with leads, deals, pipelines, and email integration.",
    status: "live",
  },
  {
    id: "i5",
    slug: "flutter-food-delivery-app",
    title: "FoodGo — Flutter Food Delivery App",
    category: "mobile",
    subcategory: "Food",
    author: "AppForge",
    authorAvatar: "AF",
    price: 79,
    rating: 4.8,
    reviews: 612,
    sales: 4120,
    thumbnail: "",
    tags: ["flutter", "dart", "ios", "android"],
    lastUpdate: "2024-11-15",
    created: "2023-03-04",
    version: "5.2.1",
    description: "Complete food delivery solution: customer app, driver app, restaurant app.",
    status: "live",
  },
  {
    id: "i6",
    slug: "wp-booking-engine",
    title: "WP Booking Engine — Reservations Plugin",
    category: "wordpress",
    subcategory: "Plugins",
    author: "PixelStack",
    authorAvatar: "PS",
    price: 35,
    rating: 4.5,
    reviews: 298,
    sales: 2840,
    thumbnail: "",
    tags: ["wordpress", "booking", "calendar", "payment"],
    lastUpdate: "2024-10-30",
    created: "2023-06-15",
    version: "2.1.0",
    description: "Hotel, salon, restaurant booking plugin with WooCommerce integration.",
    status: "live",
  },
  {
    id: "i7",
    slug: "vue-pos-system",
    title: "Vue POS — Point of Sale System",
    category: "javascript",
    subcategory: "POS",
    author: "DevOrbit",
    authorAvatar: "DO",
    price: 45,
    rating: 4.7,
    reviews: 187,
    sales: 1640,
    thumbnail: "",
    tags: ["vue", "pos", "retail", "javascript"],
    lastUpdate: "2024-12-08",
    created: "2023-09-22",
    version: "1.8.0",
    description: "Modern POS system with inventory, receipts, and multi-store support.",
    status: "live",
  },
  {
    id: "i8",
    slug: "elementor-mega-addons",
    title: "Mega Addons for Elementor — 200+ Widgets",
    category: "wordpress",
    subcategory: "Plugins",
    author: "ThemeNest",
    authorAvatar: "TN",
    price: 29,
    rating: 4.9,
    reviews: 3420,
    sales: 24500,
    thumbnail: "",
    tags: ["elementor", "wordpress", "widgets"],
    lastUpdate: "2024-12-12",
    created: "2021-05-10",
    version: "8.0.2",
    description: "The largest collection of Elementor addons. Sliders, forms, animations and more.",
    status: "live",
  },
  {
    id: "i9",
    slug: "react-native-chat-app",
    title: "ChatRN — React Native Chat & Messenger",
    category: "mobile",
    subcategory: "Social",
    author: "AppForge",
    authorAvatar: "AF",
    price: 69,
    rating: 4.6,
    reviews: 245,
    sales: 1980,
    thumbnail: "",
    tags: ["react-native", "chat", "firebase"],
    lastUpdate: "2024-11-20",
    created: "2023-02-14",
    version: "3.4.0",
    description: "1-to-1, group chats, voice notes, file sharing, push notifications.",
    status: "live",
  },
  {
    id: "i10",
    slug: "django-saas-starter",
    title: "Django SaaS Starter Kit",
    category: "php-scripts",
    subcategory: "Starter",
    author: "CodeMatrix",
    authorAvatar: "CM",
    price: 55,
    rating: 4.7,
    reviews: 156,
    sales: 1240,
    thumbnail: "",
    tags: ["django", "python", "saas", "stripe"],
    lastUpdate: "2024-12-03",
    created: "2023-07-01",
    version: "2.0.0",
    description: "Production Django SaaS boilerplate with multi-tenancy and Stripe billing.",
    status: "live",
  },
  {
    id: "i11",
    slug: "tailwind-landing-bundle",
    title: "Landwind — 30 Tailwind Landing Pages",
    category: "html-templates",
    subcategory: "Landing",
    author: "ThemeNest",
    authorAvatar: "TN",
    price: 24,
    rating: 4.8,
    reviews: 1820,
    sales: 15600,
    thumbnail: "",
    tags: ["tailwind", "landing", "html"],
    lastUpdate: "2024-11-25",
    created: "2022-12-08",
    version: "4.5.0",
    description: "30 conversion-optimized landing pages built with Tailwind CSS.",
    status: "live",
  },
  {
    id: "i12",
    slug: "woocommerce-multivendor",
    title: "WC Multi-Vendor — Marketplace Plugin",
    category: "ecommerce",
    subcategory: "Marketplace",
    author: "PixelStack",
    authorAvatar: "PS",
    price: 89,
    rating: 4.5,
    reviews: 412,
    sales: 3890,
    thumbnail: "",
    tags: ["woocommerce", "multivendor", "wordpress"],
    lastUpdate: "2024-12-09",
    created: "2022-03-18",
    version: "5.1.0",
    description: "Turn your WooCommerce store into a multi-vendor marketplace.",
    status: "live",
  },
];

export const SUBMISSIONS: MarketItem[] = [
  {
    id: "s1",
    slug: "node-realtime-board",
    title: "TaskBoard Pro — Realtime Kanban (Node.js)",
    category: "php-scripts",
    subcategory: "Productivity",
    author: "NewDev99",
    authorAvatar: "ND",
    price: 32,
    rating: 0,
    reviews: 0,
    sales: 0,
    thumbnail: "",
    tags: ["node", "socket.io"],
    lastUpdate: "2024-12-14",
    created: "2024-12-14",
    version: "1.0.0",
    description: "Submitted for review.",
    status: "pending",
  },
  {
    id: "s2",
    slug: "swift-fitness-tracker",
    title: "FitTrack — Swift Fitness Tracker",
    category: "mobile",
    subcategory: "Health",
    author: "iOSGuru",
    authorAvatar: "IG",
    price: 45,
    rating: 0,
    reviews: 0,
    sales: 0,
    thumbnail: "",
    tags: ["swift", "ios", "healthkit"],
    lastUpdate: "2024-12-13",
    created: "2024-12-13",
    version: "1.0.0",
    description: "Pending review.",
    status: "pending",
  },
  {
    id: "s3",
    slug: "wp-newsletter-light",
    title: "Newsletter Light — WP Plugin",
    category: "wordpress",
    subcategory: "Plugins",
    author: "PluginLab",
    authorAvatar: "PL",
    price: 19,
    rating: 0,
    reviews: 0,
    sales: 0,
    thumbnail: "",
    tags: ["wordpress", "newsletter"],
    lastUpdate: "2024-12-12",
    created: "2024-12-12",
    version: "1.0.0",
    description: "Submitted; needs documentation.",
    status: "soft_rejected",
  },
  {
    id: "s4",
    slug: "react-charts-pack",
    title: "ChartPack — 40 React Charts",
    category: "javascript",
    subcategory: "UI",
    author: "VizMaster",
    authorAvatar: "VM",
    price: 29,
    rating: 0,
    reviews: 0,
    sales: 0,
    thumbnail: "",
    tags: ["react", "charts", "d3"],
    lastUpdate: "2024-12-11",
    created: "2024-12-11",
    version: "1.0.0",
    description: "Awaiting QA.",
    status: "pending",
  },
  {
    id: "s5",
    slug: "old-html-template",
    title: "Vintage HTML Template",
    category: "html-templates",
    subcategory: "Other",
    author: "OldTimer",
    authorAvatar: "OT",
    price: 12,
    rating: 0,
    reviews: 0,
    sales: 0,
    thumbnail: "",
    tags: ["html", "css"],
    lastUpdate: "2024-12-10",
    created: "2024-12-10",
    version: "1.0.0",
    description: "Rejected — does not meet quality standards.",
    status: "rejected",
  },
];

export const AUTHORS = [
  {
    id: "a1",
    username: "PixelStack",
    avatar: "PS",
    country: "United Kingdom",
    joined: "2018-03-12",
    items: 24,
    sales: 42180,
    rating: 4.7,
    earnings: 184500,
    level: "Elite Author",
    featured: true,
  },
  {
    id: "a2",
    username: "ThemeNest",
    avatar: "TN",
    country: "United States",
    joined: "2017-06-08",
    items: 38,
    sales: 89420,
    rating: 4.8,
    earnings: 312000,
    level: "Power Elite",
    featured: true,
  },
  {
    id: "a3",
    username: "DevOrbit",
    avatar: "DO",
    country: "Germany",
    joined: "2019-11-22",
    items: 16,
    sales: 18420,
    rating: 4.7,
    earnings: 98000,
    level: "Elite Author",
    featured: false,
  },
  {
    id: "a4",
    username: "CodeMatrix",
    avatar: "CM",
    country: "India",
    joined: "2020-02-14",
    items: 12,
    sales: 7240,
    rating: 4.6,
    earnings: 42500,
    level: "Author L4",
    featured: false,
  },
  {
    id: "a5",
    username: "AppForge",
    avatar: "AF",
    country: "Canada",
    joined: "2019-08-30",
    items: 9,
    sales: 9120,
    rating: 4.7,
    earnings: 78400,
    level: "Author L5",
    featured: true,
  },
  {
    id: "a6",
    username: "VizMaster",
    avatar: "VM",
    country: "Australia",
    joined: "2021-05-17",
    items: 6,
    sales: 2840,
    rating: 4.5,
    earnings: 18900,
    level: "Author L3",
    featured: false,
  },
];

export const CATEGORY_TREE = [
  {
    slug: "wordpress",
    title: "WordPress",
    count: 45230,
    subs: ["Themes", "Plugins", "Business", "Blog", "Portfolio", "eCommerce"],
  },
  {
    slug: "html-templates",
    title: "HTML Templates",
    count: 12840,
    subs: ["Admin", "Landing", "Retail", "Corporate", "Portfolio"],
  },
  {
    slug: "ecommerce",
    title: "eCommerce",
    count: 8120,
    subs: ["Shopify", "WooCommerce", "Magento", "Marketplace"],
  },
  {
    slug: "php-scripts",
    title: "PHP Scripts",
    count: 9450,
    subs: ["CRM", "CMS", "Productivity", "Starter", "Forms"],
  },
  {
    slug: "javascript",
    title: "JavaScript",
    count: 6230,
    subs: ["UI", "POS", "Charts", "Forms", "Tools"],
  },
  {
    slug: "mobile",
    title: "Mobile",
    count: 4120,
    subs: ["Food", "Social", "Health", "Fitness", "Travel"],
  },
  {
    slug: "themes",
    title: "CMS Themes",
    count: 7890,
    subs: ["Drupal", "Joomla", "Ghost", "Concrete5"],
  },
  { slug: "plugins", title: "Plugins", count: 5430, subs: ["jQuery", "Vue", "React", "Angular"] },
];
