// AI API Configurations
// 100+ AI APIs with configuration-ready structure for plug-and-play system

export interface AIAPIConfig {
  id: string;
  name: string;
  type: 'text' | 'image' | 'seo' | 'analytics' | 'translation' | 'voice' | 'trend' | 'chat' | 'coding' | 'multi';
  apiUrl: string;
  apiKey?: string;
  fallbackPriority: number;
  status: 'active' | 'inactive';
  usageLimit: string;
  costPerRequest?: number;
  description?: string;
}

// TEXT / CONTENT AI (1-20)
export const textContentAIAPIs: AIAPIConfig[] = [
  {
    id: 'openai-gpt',
    name: 'OpenAI GPT',
    type: 'text',
    apiUrl: 'https://api.openai.com/v1/chat/completions',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.002,
    description: 'Advanced language model for text generation and analysis',
  },
  {
    id: 'anthropic-claude',
    name: 'Anthropic Claude',
    type: 'text',
    apiUrl: 'https://api.anthropic.com/v1/messages',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.003,
    description: 'Constitutional AI for safe and helpful responses',
  },
  {
    id: 'google-gemini',
    name: 'Google Gemini API',
    type: 'text',
    apiUrl: 'https://generativelanguage.googleapis.com/v1beta/models',
    fallbackPriority: 3,
    status: 'active',
    usageLimit: '1500 requests/day',
    costPerRequest: 0.001,
    description: 'Google\'s multimodal AI model',
  },
  {
    id: 'cohere-ai',
    name: 'Cohere AI',
    type: 'text',
    apiUrl: 'https://api.cohere.ai/v1/generate',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.0015,
    description: 'Natural language processing and generation',
  },
  {
    id: 'ai21-labs',
    name: 'AI21 Labs',
    type: 'text',
    apiUrl: 'https://api.ai21.com/studio/v1/complete',
    fallbackPriority: 5,
    status: 'active',
    usageLimit: '500 requests/day',
    costPerRequest: 0.002,
    description: 'Jurassic language models for text generation',
  },
  {
    id: 'deepseek-api',
    name: 'DeepSeek API',
    type: 'text',
    apiUrl: 'https://api.deepseek.com/v1/chat/completions',
    fallbackPriority: 6,
    status: 'active',
    usageLimit: '2000 requests/day',
    costPerRequest: 0.0001,
    description: 'Cost-effective Chinese AI model',
  },
  {
    id: 'perplexity-ai',
    name: 'Perplexity AI',
    type: 'text',
    apiUrl: 'https://api.perplexity.ai/chat/completions',
    fallbackPriority: 7,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.001,
    description: 'AI-powered search and answer engine',
  },
  {
    id: 'mistral-ai',
    name: 'Mistral AI',
    type: 'text',
    apiUrl: 'https://api.mistral.ai/v1/chat/completions',
    fallbackPriority: 8,
    status: 'active',
    usageLimit: '1500 requests/day',
    costPerRequest: 0.0007,
    description: 'Open-source French AI company',
  },
  {
    id: 'groq-ai',
    name: 'Groq AI',
    type: 'text',
    apiUrl: 'https://api.groq.com/openai/v1/chat/completions',
    fallbackPriority: 9,
    status: 'active',
    usageLimit: '5000 requests/day',
    costPerRequest: 0.0001,
    description: 'Ultra-fast AI inference',
  },
  {
    id: 'huggingface-inference',
    name: 'HuggingFace Inference',
    type: 'text',
    apiUrl: 'https://api-inference.huggingface.co/models',
    fallbackPriority: 10,
    status: 'active',
    usageLimit: '10000 requests/day',
    costPerRequest: 0.0005,
    description: 'Open-source model inference API',
  },
  {
    id: 'writer-ai',
    name: 'Writer AI',
    type: 'text',
    apiUrl: 'https://api.writer.com/v1/content/generate',
    fallbackPriority: 11,
    status: 'inactive',
    usageLimit: '500 requests/day',
    costPerRequest: 0.005,
    description: 'Enterprise content generation platform',
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai API',
    type: 'text',
    apiUrl: 'https://api.copy.ai/v1/generate',
    fallbackPriority: 12,
    status: 'inactive',
    usageLimit: '300 requests/day',
    costPerRequest: 0.01,
    description: 'Marketing copy generation',
  },
  {
    id: 'jasper-ai',
    name: 'Jasper AI API',
    type: 'text',
    apiUrl: 'https://api.jasper.ai/v1/generate',
    fallbackPriority: 13,
    status: 'inactive',
    usageLimit: '500 requests/day',
    costPerRequest: 0.008,
    description: 'AI content assistant for marketers',
  },
  {
    id: 'rytr-api',
    name: 'Rytr API',
    type: 'text',
    apiUrl: 'https://api.rytr.me/v1/generate',
    fallbackPriority: 14,
    status: 'inactive',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.003,
    description: 'AI writing assistant',
  },
  {
    id: 'peppertype-ai',
    name: 'Peppertype AI',
    type: 'text',
    apiUrl: 'https://api.peppertype.ai/v1/generate',
    fallbackPriority: 15,
    status: 'inactive',
    usageLimit: '500 requests/day',
    costPerRequest: 0.004,
    description: 'Content generation platform',
  },
  {
    id: 'sudowrite-api',
    name: 'Sudowrite API',
    type: 'text',
    apiUrl: 'https://api.sudowrite.com/v1/generate',
    fallbackPriority: 16,
    status: 'inactive',
    usageLimit: '300 requests/day',
    costPerRequest: 0.006,
    description: 'AI writing tool for fiction writers',
  },
  {
    id: 'anyword-ai',
    name: 'Anyword AI',
    type: 'text',
    apiUrl: 'https://api.anyword.com/v1/generate',
    fallbackPriority: 17,
    status: 'inactive',
    usageLimit: '500 requests/day',
    costPerRequest: 0.005,
    description: 'Data-driven copywriting AI',
  },
  {
    id: 'neuraltext-api',
    name: 'NeuralText API',
    type: 'text',
    apiUrl: 'https://api.neuraltext.com/v1/generate',
    fallbackPriority: 18,
    status: 'inactive',
    usageLimit: '400 requests/day',
    costPerRequest: 0.004,
    description: 'SEO-focused content generation',
  },
  {
    id: 'frase-ai',
    name: 'Frase AI',
    type: 'text',
    apiUrl: 'https://api.frase.io/v1/generate',
    fallbackPriority: 19,
    status: 'inactive',
    usageLimit: '300 requests/day',
    costPerRequest: 0.007,
    description: 'Content optimization and research',
  },
  {
    id: 'writesonic-api',
    name: 'Writesonic API',
    type: 'text',
    apiUrl: 'https://api.writesonic.com/v1/generate',
    fallbackPriority: 20,
    status: 'inactive',
    usageLimit: '500 requests/day',
    costPerRequest: 0.003,
    description: 'AI writing and marketing copy',
  },
];

// SEO AI (21-30)
export const seoAIAPIs: AIAPIConfig[] = [
  {
    id: 'surfer-seo',
    name: 'Surfer SEO API',
    type: 'seo',
    apiUrl: 'https://api.surferseo.com/v1',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '100 requests/day',
    costPerRequest: 0.05,
    description: 'Content optimization for SEO',
  },
  {
    id: 'clearscope-api',
    name: 'Clearscope API',
    type: 'seo',
    apiUrl: 'https://api.clearscope.io/v1',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: '100 requests/day',
    costPerRequest: 0.06,
    description: 'Content optimization platform',
  },
  {
    id: 'marketmuse-api',
    name: 'MarketMuse API',
    type: 'seo',
    apiUrl: 'https://api.marketmuse.com/v1',
    fallbackPriority: 3,
    status: 'active',
    usageLimit: '50 requests/day',
    costPerRequest: 0.08,
    description: 'AI-driven content strategy',
  },
  {
    id: 'scalenut-api',
    name: 'Scalenut API',
    type: 'seo',
    apiUrl: 'https://api.scalenut.com/v1',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '200 requests/day',
    costPerRequest: 0.03,
    description: 'SEO and content marketing platform',
  },
  {
    id: 'rankiq-api',
    name: 'RankIQ API',
    type: 'seo',
    apiUrl: 'https://api.rankiq.com/v1',
    fallbackPriority: 5,
    status: 'inactive',
    usageLimit: '100 requests/day',
    costPerRequest: 0.04,
    description: 'Keyword research and SEO',
  },
  {
    id: 'semrush-api',
    name: 'SEMrush API',
    type: 'seo',
    apiUrl: 'https://api.semrush.com',
    fallbackPriority: 6,
    status: 'active',
    usageLimit: '5000 requests/day',
    costPerRequest: 0.001,
    description: 'Comprehensive SEO toolkit',
  },
  {
    id: 'ahrefs-api',
    name: 'Ahrefs API',
    type: 'seo',
    apiUrl: 'https://apiv2.ahrefs.com',
    fallbackPriority: 7,
    status: 'active',
    usageLimit: '5000 requests/day',
    costPerRequest: 0.001,
    description: 'Backlink analysis and SEO',
  },
  {
    id: 'moz-api',
    name: 'Moz API',
    type: 'seo',
    apiUrl: 'https://api.moz.com/v1',
    fallbackPriority: 8,
    status: 'active',
    usageLimit: '25000 requests/day',
    costPerRequest: 0.0005,
    description: 'SEO metrics and insights',
  },
  {
    id: 'ubersuggest-api',
    name: 'Ubersuggest API',
    type: 'seo',
    apiUrl: 'https://api.neilpatel.com/v1',
    fallbackPriority: 9,
    status: 'inactive',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.002,
    description: 'Keyword research and SEO audit',
  },
  {
    id: 'se-ranking-api',
    name: 'SE Ranking API',
    type: 'seo',
    apiUrl: 'https://api.seranking.com',
    fallbackPriority: 10,
    status: 'inactive',
    usageLimit: '2000 requests/day',
    costPerRequest: 0.0015,
    description: 'All-in-one SEO platform',
  },
];

// TRANSLATION AI (31-40)
export const translationAIAPIs: AIAPIConfig[] = [
  {
    id: 'google-translate',
    name: 'Google Translate API',
    type: 'translation',
    apiUrl: 'https://translation.googleapis.com/language/translate/v2',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '1000000 characters/day',
    costPerRequest: 0.00002,
    description: 'Google\'s translation service',
  },
  {
    id: 'deepl-api',
    name: 'DeepL API',
    type: 'translation',
    apiUrl: 'https://api-free.deepl.com/v2/translate',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: '500000 characters/month',
    costPerRequest: 0.000025,
    description: 'High-quality neural translation',
  },
  {
    id: 'microsoft-translator',
    name: 'Microsoft Translator',
    type: 'translation',
    apiUrl: 'https://api.cognitive.microsofttranslator.com/translate',
    fallbackPriority: 3,
    status: 'active',
    usageLimit: '2000000 characters/month',
    costPerRequest: 0.00001,
    description: 'Microsoft\'s translation service',
  },
  {
    id: 'amazon-translate',
    name: 'Amazon Translate',
    type: 'translation',
    apiUrl: 'https://translate.amazonaws.com',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '2000000 characters/month',
    costPerRequest: 0.000015,
    description: 'AWS translation service',
  },
  {
    id: 'libretranslate',
    name: 'LibreTranslate',
    type: 'translation',
    apiUrl: 'https://libretranslate.com/translate',
    fallbackPriority: 5,
    status: 'active',
    usageLimit: '100000 characters/day',
    costPerRequest: 0,
    description: 'Free open-source translation',
  },
  {
    id: 'lingva-api',
    name: 'Lingva API',
    type: 'translation',
    apiUrl: 'https://lingva.ml/api/v1',
    fallbackPriority: 6,
    status: 'active',
    usageLimit: '50000 characters/day',
    costPerRequest: 0,
    description: 'Privacy-focused translation',
  },
  {
    id: 'yandex-translate',
    name: 'Yandex Translate',
    type: 'translation',
    apiUrl: 'https://translate.yandex.net/api/v1.5/tr.json/translate',
    fallbackPriority: 7,
    status: 'inactive',
    usageLimit: '1000000 characters/day',
    costPerRequest: 0,
    description: 'Yandex translation service',
  },
  {
    id: 'modernmt-api',
    name: 'ModernMT API',
    type: 'translation',
    apiUrl: 'https://api.modernmt.com/translate',
    fallbackPriority: 8,
    status: 'inactive',
    usageLimit: '100000 characters/month',
    costPerRequest: 0.00003,
    description: 'Enterprise neural translation',
  },
  {
    id: 'textunited-api',
    name: 'TextUnited API',
    type: 'translation',
    apiUrl: 'https://api.textunited.com/v1',
    fallbackPriority: 9,
    status: 'inactive',
    usageLimit: '50000 characters/month',
    costPerRequest: 0.00004,
    description: 'Translation management platform',
  },
  {
    id: 'systran-api',
    name: 'SYSTRAN API',
    type: 'translation',
    apiUrl: 'https://api.systran.net/translation',
    fallbackPriority: 10,
    status: 'inactive',
    usageLimit: '100000 characters/month',
    costPerRequest: 0.000035,
    description: 'Professional translation services',
  },
];

// IMAGE AI (41-50)
export const imageAIAPIs: AIAPIConfig[] = [
  {
    id: 'stability-ai',
    name: 'Stability AI',
    type: 'image',
    apiUrl: 'https://api.stability.ai/v1/generation',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '1000 images/day',
    costPerRequest: 0.02,
    description: 'Stable Diffusion image generation',
  },
  {
    id: 'dalle-api',
    name: 'DALL·E API',
    type: 'image',
    apiUrl: 'https://api.openai.com/v1/images/generations',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: '500 images/day',
    costPerRequest: 0.04,
    description: 'OpenAI image generation',
  },
  {
    id: 'midjourney',
    name: 'Midjourney (unofficial)',
    type: 'image',
    apiUrl: 'https://api.midjourney.com/v1',
    fallbackPriority: 3,
    status: 'inactive',
    usageLimit: '200 images/day',
    costPerRequest: 0.03,
    description: 'High-quality image generation',
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo AI',
    type: 'image',
    apiUrl: 'https://api.leonardo.ai/v1',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '1500 images/day',
    costPerRequest: 0.015,
    description: 'AI art generation platform',
  },
  {
    id: 'runway-ml',
    name: 'Runway ML',
    type: 'image',
    apiUrl: 'https://api.runwayml.com/v1',
    fallbackPriority: 5,
    status: 'active',
    usageLimit: '500 images/day',
    costPerRequest: 0.025,
    description: 'Creative AI tools',
  },
  {
    id: 'replicate-api',
    name: 'Replicate API',
    type: 'image',
    apiUrl: 'https://api.replicate.com/v1',
    fallbackPriority: 6,
    status: 'active',
    usageLimit: '1000 images/day',
    costPerRequest: 0.01,
    description: 'Open-source model hosting',
  },
  {
    id: 'deepai-image',
    name: 'DeepAI Image',
    type: 'image',
    apiUrl: 'https://api.deepai.org/text2img',
    fallbackPriority: 7,
    status: 'active',
    usageLimit: '100 images/day',
    costPerRequest: 0.005,
    description: 'Simple image generation',
  },
  {
    id: 'craiyon-api',
    name: 'Craiyon API',
    type: 'image',
    apiUrl: 'https://api.craiyon.com/v3',
    fallbackPriority: 8,
    status: 'active',
    usageLimit: '200 images/day',
    costPerRequest: 0,
    description: 'Free DALL-E mini',
  },
  {
    id: 'playground-ai',
    name: 'Playground AI',
    type: 'image',
    apiUrl: 'https://api.playgroundai.com/v1',
    fallbackPriority: 9,
    status: 'inactive',
    usageLimit: '500 images/day',
    costPerRequest: 0.02,
    description: 'AI image generation',
  },
  {
    id: 'clipdrop-api',
    name: 'ClipDrop API',
    type: 'image',
    apiUrl: 'https://clipdrop-api.co/api/v1',
    fallbackPriority: 10,
    status: 'inactive',
    usageLimit: '300 images/day',
    costPerRequest: 0.03,
    description: 'Image editing and generation',
  },
];

// VOICE AI (51-60)
export const voiceAIAPIs: AIAPIConfig[] = [
  {
    id: 'elevenlabs-api',
    name: 'ElevenLabs API',
    type: 'voice',
    apiUrl: 'https://api.elevenlabs.io/v1',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '10000 characters/month',
    costPerRequest: 0.0003,
    description: 'High-quality text-to-speech',
  },
  {
    id: 'playht-api',
    name: 'PlayHT API',
    type: 'voice',
    apiUrl: 'https://api.play.ht/api/v1',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: '5000 characters/month',
    costPerRequest: 0.00025,
    description: 'AI voice generation',
  },
  {
    id: 'resemble-ai',
    name: 'Resemble AI',
    type: 'voice',
    apiUrl: 'https://api.resemble.ai/v2',
    fallbackPriority: 3,
    status: 'active',
    usageLimit: '1000 minutes/month',
    costPerRequest: 0.001,
    description: 'Voice cloning and TTS',
  },
  {
    id: 'murf-ai',
    name: 'Murf AI',
    type: 'voice',
    apiUrl: 'https://api.murf.ai/v1',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '2000 minutes/month',
    costPerRequest: 0.0008,
    description: 'AI voiceover platform',
  },
  {
    id: 'lovo-ai',
    name: 'Lovo AI',
    type: 'voice',
    apiUrl: 'https://api.lovo.ai/v1',
    fallbackPriority: 5,
    status: 'active',
    usageLimit: '1500 minutes/month',
    costPerRequest: 0.0007,
    description: 'Text-to-speech platform',
  },
  {
    id: 'coqui-tts',
    name: 'Coqui TTS',
    type: 'voice',
    apiUrl: 'https://api.coqui.ai/v1',
    fallbackPriority: 6,
    status: 'active',
    usageLimit: '5000 characters/day',
    costPerRequest: 0,
    description: 'Open-source TTS',
  },
  {
    id: 'google-tts',
    name: 'Google TTS',
    type: 'voice',
    apiUrl: 'https://texttospeech.googleapis.com/v1/text:synthesize',
    fallbackPriority: 7,
    status: 'active',
    usageLimit: '1000000 characters/month',
    costPerRequest: 0.000016,
    description: 'Google text-to-speech',
  },
  {
    id: 'amazon-polly',
    name: 'Amazon Polly',
    type: 'voice',
    apiUrl: 'https://polly.amazonaws.com',
    fallbackPriority: 8,
    status: 'active',
    usageLimit: '5000000 characters/month',
    costPerRequest: 0.000004,
    description: 'AWS text-to-speech',
  },
  {
    id: 'azure-speech',
    name: 'Azure Speech',
    type: 'voice',
    apiUrl: 'https://eastus.tts.speech.microsoft.com/cognitiveservices/v1',
    fallbackPriority: 9,
    status: 'active',
    usageLimit: '5000000 characters/month',
    costPerRequest: 0.000016,
    description: 'Microsoft text-to-speech',
  },
  {
    id: 'wellsaid-labs',
    name: 'WellSaid Labs',
    type: 'voice',
    apiUrl: 'https://api.well Saidlabs.com/v1',
    fallbackPriority: 10,
    status: 'inactive',
    usageLimit: '1000 minutes/month',
    costPerRequest: 0.0015,
    description: 'AI voice generation',
  },
];

// ANALYTICS AI (61-70)
export const analyticsAIAPIs: AIAPIConfig[] = [
  {
    id: 'google-analytics',
    name: 'Google Analytics API',
    type: 'analytics',
    apiUrl: 'https://analyticsreporting.googleapis.com/v4',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '10000 requests/day',
    costPerRequest: 0,
    description: 'Google analytics and reporting',
  },
  {
    id: 'mixpanel-api',
    name: 'Mixpanel API',
    type: 'analytics',
    apiUrl: 'https://api.mixpanel.com',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: '1000000 events/month',
    costPerRequest: 0,
    description: 'Product analytics platform',
  },
  {
    id: 'amplitude-api',
    name: 'Amplitude API',
    type: 'analytics',
    apiUrl: 'https://api.amplitude.com',
    fallbackPriority: 3,
    status: 'active',
    usageLimit: '1000000 events/month',
    costPerRequest: 0,
    description: 'Digital analytics platform',
  },
  {
    id: 'heap-analytics',
    name: 'Heap Analytics',
    type: 'analytics',
    apiUrl: 'https://api.heapanalytics.com',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '100000 events/month',
    costPerRequest: 0,
    description: 'Digital insights platform',
  },
  {
    id: 'plausible-api',
    name: 'Plausible API',
    type: 'analytics',
    apiUrl: 'https://plausible.io/api',
    fallbackPriority: 5,
    status: 'active',
    usageLimit: '100000 pageviews/month',
    costPerRequest: 0,
    description: 'Privacy-focused analytics',
  },
  {
    id: 'posthog-api',
    name: 'PostHog API',
    type: 'analytics',
    apiUrl: 'https://app.posthog.com/api',
    fallbackPriority: 6,
    status: 'active',
    usageLimit: '1000000 events/month',
    costPerRequest: 0,
    description: 'Open-source product analytics',
  },
  {
    id: 'segment-api',
    name: 'Segment API',
    type: 'analytics',
    apiUrl: 'https://api.segment.io/v1',
    fallbackPriority: 7,
    status: 'active',
    usageLimit: '1000000 events/month',
    costPerRequest: 0,
    description: 'Customer data platform',
  },
  {
    id: 'matomo-api',
    name: 'Matomo API',
    type: 'analytics',
    apiUrl: 'https://demo.matomo.org',
    fallbackPriority: 8,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'Open-source analytics',
  },
  {
    id: 'adobe-analytics',
    name: 'Adobe Analytics',
    type: 'analytics',
    apiUrl: 'https://analytics.adobe.io/api',
    fallbackPriority: 9,
    status: 'inactive',
    usageLimit: '100000 requests/day',
    costPerRequest: 0.001,
    description: 'Enterprise analytics',
  },
  {
    id: 'kissmetrics',
    name: 'Kissmetrics',
    type: 'analytics',
    apiUrl: 'https://api.kissmetrics.com',
    fallbackPriority: 10,
    status: 'inactive',
    usageLimit: '50000 events/month',
    costPerRequest: 0.0005,
    description: 'Product analytics',
  },
];

// TREND / DATA AI (71-80)
export const trendDataAIAPIs: AIAPIConfig[] = [
  {
    id: 'google-trends',
    name: 'Google Trends API',
    type: 'trend',
    apiUrl: 'https://trends.google.com/trends/api',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0,
    description: 'Google search trend data',
  },
  {
    id: 'exploding-topics',
    name: 'Exploding Topics',
    type: 'trend',
    apiUrl: 'https://api.explodingtopics.com/v1',
    fallbackPriority: 2,
    status: 'inactive',
    usageLimit: '100 requests/day',
    costPerRequest: 0.01,
    description: 'Trend discovery platform',
  },
  {
    id: 'trendhunter-api',
    name: 'TrendHunter API',
    type: 'trend',
    apiUrl: 'https://api.trendhunter.com/v1',
    fallbackPriority: 3,
    status: 'inactive',
    usageLimit: '50 requests/day',
    costPerRequest: 0.02,
    description: 'Trend spotting platform',
  },
  {
    id: 'buzzsumo-api',
    name: 'BuzzSumo API',
    type: 'trend',
    apiUrl: 'https://api.buzzsumo.com',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.001,
    description: 'Content discovery and analytics',
  },
  {
    id: 'feedly-api',
    name: 'Feedly API',
    type: 'trend',
    apiUrl: 'https://api.feedly.com/v3',
    fallbackPriority: 5,
    status: 'active',
    usageLimit: '10000 requests/day',
    costPerRequest: 0,
    description: 'Content aggregation',
  },
  {
    id: 'reddit-api',
    name: 'Reddit API',
    type: 'trend',
    apiUrl: 'https://www.reddit.com/dev/api',
    fallbackPriority: 6,
    status: 'active',
    usageLimit: '600 requests/minute',
    costPerRequest: 0,
    description: 'Reddit data and trends',
  },
  {
    id: 'twitter-api',
    name: 'Twitter API',
    type: 'trend',
    apiUrl: 'https://api.twitter.com/2',
    fallbackPriority: 7,
    status: 'active',
    usageLimit: '500000 tweets/month',
    costPerRequest: 0,
    description: 'Twitter data and trends',
  },
  {
    id: 'newsapi',
    name: 'NewsAPI',
    type: 'trend',
    apiUrl: 'https://newsapi.org/v2',
    fallbackPriority: 8,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0,
    description: 'News aggregation API',
  },
  {
    id: 'gdelt-api',
    name: 'GDELT API',
    type: 'trend',
    apiUrl: 'https://api.gdeltproject.org/api/v2',
    fallbackPriority: 9,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'Global event database',
  },
  {
    id: 'kaggle-api',
    name: 'Kaggle API',
    type: 'trend',
    apiUrl: 'https://www.kaggle.com/api/v1',
    fallbackPriority: 10,
    status: 'active',
    usageLimit: '100 requests/hour',
    costPerRequest: 0,
    description: 'Datasets and competitions',
  },
];

// CHAT / BOT AI (81-90)
export const chatBotAIAPIs: AIAPIConfig[] = [
  {
    id: 'dialogflow',
    name: 'Dialogflow',
    type: 'chat',
    apiUrl: 'https://dialogflow.googleapis.com/v2',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '180 requests/minute',
    costPerRequest: 0,
    description: 'Google conversational AI',
  },
  {
    id: 'rasa-ai',
    name: 'Rasa AI',
    type: 'chat',
    apiUrl: 'https://api.rasa.com/v1',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'Open-source conversational AI',
  },
  {
    id: 'botpress-api',
    name: 'Botpress API',
    type: 'chat',
    apiUrl: 'https://api.botpress.cloud/v1',
    fallbackPriority: 3,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0,
    description: 'Open-source chatbot platform',
  },
  {
    id: 'tidio-ai',
    name: 'Tidio AI',
    type: 'chat',
    apiUrl: 'https://api.tidio.com/v1',
    fallbackPriority: 4,
    status: 'inactive',
    usageLimit: '500 conversations/day',
    costPerRequest: 0.005,
    description: 'Chatbot and live chat',
  },
  {
    id: 'drift-api',
    name: 'Drift API',
    type: 'chat',
    apiUrl: 'https://api.drift.com/v1',
    fallbackPriority: 5,
    status: 'inactive',
    usageLimit: '1000 conversations/day',
    costPerRequest: 0.008,
    description: 'Conversational marketing',
  },
  {
    id: 'intercom-ai',
    name: 'Intercom AI',
    type: 'chat',
    apiUrl: 'https://api.intercom.io/v1',
    fallbackPriority: 6,
    status: 'inactive',
    usageLimit: '500 conversations/day',
    costPerRequest: 0.01,
    description: 'Customer messaging',
  },
  {
    id: 'crisp-chat-api',
    name: 'Crisp Chat API',
    type: 'chat',
    apiUrl: 'https://api.crisp.chat/v1',
    fallbackPriority: 7,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'Live chat and chatbot',
  },
  {
    id: 'livechat-api',
    name: 'LiveChat API',
    type: 'chat',
    apiUrl: 'https://api.livechatinc.com/v3.3',
    fallbackPriority: 8,
    status: 'inactive',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.005,
    description: 'Customer service platform',
  },
  {
    id: 'manychat-api',
    name: 'ManyChat API',
    type: 'chat',
    apiUrl: 'https://api.manychat.com/v2',
    fallbackPriority: 9,
    status: 'inactive',
    usageLimit: '1000 messages/day',
    costPerRequest: 0.003,
    description: 'Facebook Messenger bot',
  },
  {
    id: 'chatfuel-api',
    name: 'Chatfuel API',
    type: 'chat',
    apiUrl: 'https://api.chatfuel.com/v1',
    fallbackPriority: 10,
    status: 'inactive',
    usageLimit: '500 messages/day',
    costPerRequest: 0.004,
    description: 'No-code chatbot platform',
  },
];

// CODING / DEV AI (91-100)
export const codingDevAIAPIs: AIAPIConfig[] = [
  {
    id: 'github-copilot',
    name: 'GitHub Copilot API',
    type: 'coding',
    apiUrl: 'https://api.githubcopilot.com',
    fallbackPriority: 1,
    status: 'inactive',
    usageLimit: 'Unlimited',
    costPerRequest: 0.01,
    description: 'AI pair programmer',
  },
  {
    id: 'codeium-api',
    name: 'Codeium API',
    type: 'coding',
    apiUrl: 'https://api.codeium.com',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'Free AI code completion',
  },
  {
    id: 'tabnine-api',
    name: 'Tabnine API',
    type: 'coding',
    apiUrl: 'https://api.tabnine.com',
    fallbackPriority: 3,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'AI code assistant',
  },
  {
    id: 'replit-ai',
    name: 'Replit AI',
    type: 'coding',
    apiUrl: 'https://api.replit.com',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.001,
    description: 'AI-powered coding',
  },
  {
    id: 'sourcegraph-cody',
    name: 'Sourcegraph Cody',
    type: 'coding',
    apiUrl: 'https://api.sourcegraph.com',
    fallbackPriority: 5,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'AI code understanding',
  },
  {
    id: 'amazon-codewhisperer',
    name: 'Amazon CodeWhisperer',
    type: 'coding',
    apiUrl: 'https://codewhisperer.us-east-1.amazonaws.com',
    fallbackPriority: 6,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'AWS code generation',
  },
  {
    id: 'codex-api',
    name: 'Codex API',
    type: 'coding',
    apiUrl: 'https://api.openai.com/v1/code',
    fallbackPriority: 7,
    status: 'inactive',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.01,
    description: 'OpenAI code generation',
  },
  {
    id: 'mutable-ai',
    name: 'Mutable AI',
    type: 'coding',
    apiUrl: 'https://api.mutable.ai',
    fallbackPriority: 8,
    status: 'inactive',
    usageLimit: '500 requests/day',
    costPerRequest: 0.005,
    description: 'AI code refactoring',
  },
  {
    id: 'blackbox-ai',
    name: 'Blackbox AI',
    type: 'coding',
    apiUrl: 'https://api.useblackbox.io',
    fallbackPriority: 9,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'AI code search',
  },
  {
    id: 'phind-api',
    name: 'Phind API',
    type: 'coding',
    apiUrl: 'https://api.phind.com',
    fallbackPriority: 10,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0,
    description: 'AI-powered code search',
  },
];

// EXTRA / MULTI PURPOSE (101-110)
export const multiPurposeAIAPIs: AIAPIConfig[] = [
  {
    id: 'zapier-ai',
    name: 'Zapier AI',
    type: 'multi',
    apiUrl: 'https://api.zapier.com/v1',
    fallbackPriority: 1,
    status: 'active',
    usageLimit: '10000 tasks/month',
    costPerRequest: 0.001,
    description: 'Automation platform with AI',
  },
  {
    id: 'make-integromat',
    name: 'Make (Integromat)',
    type: 'multi',
    apiUrl: 'https://api.make.com',
    fallbackPriority: 2,
    status: 'active',
    usageLimit: '10000 operations/month',
    costPerRequest: 0.001,
    description: 'Visual automation platform',
  },
  {
    id: 'n8n-ai',
    name: 'n8n AI workflows',
    type: 'multi',
    apiUrl: 'https://api.n8n.io',
    fallbackPriority: 3,
    status: 'active',
    usageLimit: 'Unlimited',
    costPerRequest: 0,
    description: 'Open-source workflow automation',
  },
  {
    id: 'pipedream-api',
    name: 'Pipedream API',
    type: 'multi',
    apiUrl: 'https://api.pipedream.com/v1',
    fallbackPriority: 4,
    status: 'active',
    usageLimit: '5000 workflows/month',
    costPerRequest: 0.001,
    description: 'Integration platform',
  },
  {
    id: 'airtable-ai',
    name: 'Airtable AI',
    type: 'multi',
    apiUrl: 'https://api.airtable.com/v0',
    fallbackPriority: 5,
    status: 'active',
    usageLimit: '5000 requests/day',
    costPerRequest: 0.002,
    description: 'Database with AI features',
  },
  {
    id: 'notion-ai',
    name: 'Notion AI API',
    type: 'multi',
    apiUrl: 'https://api.notion.com/v1',
    fallbackPriority: 6,
    status: 'inactive',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.003,
    description: 'Productivity with AI',
  },
  {
    id: 'slack-ai',
    name: 'Slack AI API',
    type: 'multi',
    apiUrl: 'https://api.slack.com/methods',
    fallbackPriority: 7,
    status: 'active',
    usageLimit: '10000 requests/day',
    costPerRequest: 0,
    description: 'Team communication with AI',
  },
  {
    id: 'discord-ai-bot',
    name: 'Discord AI Bot API',
    type: 'multi',
    apiUrl: 'https://discord.com/api/v10',
    fallbackPriority: 8,
    status: 'active',
    usageLimit: '10000 requests/day',
    costPerRequest: 0,
    description: 'Discord bot with AI',
  },
  {
    id: 'shopify-ai',
    name: 'Shopify AI',
    type: 'multi',
    apiUrl: 'https://api.shopify.com',
    fallbackPriority: 9,
    status: 'active',
    usageLimit: '1000 requests/day',
    costPerRequest: 0.002,
    description: 'E-commerce with AI',
  },
  {
    id: 'firebase-ai',
    name: 'Firebase AI Extensions',
    type: 'multi',
    apiUrl: 'https://firebase.googleapis.com/v1',
    fallbackPriority: 10,
    status: 'active',
    usageLimit: '10000 requests/day',
    costPerRequest: 0,
    description: 'Backend with AI extensions',
  },
];

// All APIs combined
export const allAIAPIs: AIAPIConfig[] = [
  ...textContentAIAPIs,
  ...seoAIAPIs,
  ...translationAIAPIs,
  ...imageAIAPIs,
  ...voiceAIAPIs,
  ...analyticsAIAPIs,
  ...trendDataAIAPIs,
  ...chatBotAIAPIs,
  ...codingDevAIAPIs,
  ...multiPurposeAIAPIs,
];

// Get APIs by type
export function getAPIsByType(type: AIAPIConfig['type']): AIAPIConfig[] {
  return allAIAPIs.filter((api) => api.type === type);
}

// Get API by ID
export function getAPIById(id: string): AIAPIConfig | undefined {
  return allAIAPIs.find((api) => api.id === id);
}

// Get active APIs
export function getActiveAPIs(): AIAPIConfig[] {
  return allAIAPIs.filter((api) => api.status === 'active');
}

// Get APIs by priority (sorted)
export function getAPIsByPriority(type?: AIAPIConfig['type']): AIAPIConfig[] {
  let apis = type ? getAPIsByType(type) : allAIAPIs;
  return apis.filter((api) => api.status === 'active').sort((a, b) => a.fallbackPriority - b.fallbackPriority);
}
